### ISSUE TITLE
Estudar Docker

### ISSUE THREAD

**Issue by pedro-cella** [ChatBot-Bino/Bot-Bino#2]

**Comment by PauloGoncalvesLima** [comment]
https://www.youtube.com/playlist?list=PLf-O3X2-mxDkiUH0r_BadgtELJ_qyrFJ_

**Comment by PauloGoncalvesLima** [comment]
https://www.youtube.com/watch?v=ETBj0oxe81o&list=PL6XT0grm_Tfje2ySztzdhp0HmCjVj5P4z&index=1

**Comment by pedro-cella** [comment]
Instalação do Docker
https://www.youtube.com/watch?v=bpbcu36t7g0

**Comment by PauloGoncalvesLima** [comment]
Reunião com o Arthur Diniz:

Registry
    Imagens: um SO encapsulado em em um arquivo
From:
    Oque nessa imagem vai ser contido (contruindo em layrs)
    Docker Build vai refazer todo o Docker
    Como é bebian tem como rodar todos os comandos debias
    WORKDIR: Muda o diretorio padrão
    EXPOSE: Faz uma conecta o host com o Docker
Microserviso:
    Docker-Compose:

CLI??

yml??

Volumes:
    Ele cria um link simbolico entre o host e o docker
    Persiste os dados do bancos de dados
    Docker volume ls
Command: Executa o programa ou aplicação
Volume:
    Facilita 

WebSocket???
ports: expoe uma porta e faz um link com o nosso websocket 

Depends_on: (Olhar mais a fundo)
    Um container não roda sem o determinado docker

NLU?? 
MOngoDB

Analise do rasa e docker Compose

NGINX:
    Load balancer??
        Aponta para a maquina com menos requisição
    ProxyReveso:
        Ele sabe em para qual maquina ele vai 
    Cache:
        Coloca o NGINX na frento do serviço para que seja mais rapido.

Escabilidade??
     Chache
Possibildade de networks: Cria redes especificas



Stages:
    Build:


    Lint:
        Verificador de escrita de codico.

    Deploy:


Env
Artifacts: Salva em HTML ????
Gitops
